import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import Header from '@/components/Header';
import Main from '@/components/Main';
import { cookies } from 'next/headers';
import { User } from '@/types/api/user';
import { UserProvider } from '@/contexts/UserProvider';
import { TooltipProvider } from '@/components/ui/tooltip';
import { redirect } from 'next/navigation';
import { CategoriesProvider } from '@/contexts/CategoriesProvider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookiesStore = await cookies();
  const token = cookiesStore.get('token')?.value;
  let user: User | null = null;

  const [userRes, categoriesRes] = await Promise.all([
    fetch(`${process.env.API_URL}/api/me`, {
      headers: {
        Accept: 'application/json',
        Authorization: `Bearer ${token}`,
      },
    }),
    fetch(`${process.env.API_URL}/api/categories`, {
      next: { revalidate: 3600 }, // 1 hour
      headers: {
        Accept: 'application/json',
      },
    }),
  ]);

  // 認証エラーだけログインへ
  if (!userRes.ok) {
    redirect('/login');
  }

  if (!categoriesRes.ok) {
    throw new Error(
      `Failed to fetch categories: ${categoriesRes.status} ${categoriesRes.statusText}`,
    );
  }

  const [userJson, categories] = await Promise.all([userRes.json(), categoriesRes.json()]);
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <TooltipProvider>
          <div className="grid h-screen grid-cols-[220px_4fr] grid-rows-[auto_1fr_auto]">
            <UserProvider initialUser={userJson.user}>
              <CategoriesProvider initialCategories={categories}>
                <Navbar />
                <Header />
                <Main>{children}</Main>
              </CategoriesProvider>
            </UserProvider>
          </div>
        </TooltipProvider>
      </body>
    </html>
  );
}
