import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import Header from '@/components/Header';
import Main from '@/components/Main';
import { cookies } from 'next/headers';
import { User } from '@/types/api/user';
import { UserProvider } from '@/contexts/UserProvider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookiesStore = await cookies();
  const token = cookiesStore.get('token')?.value;
  let user: User | null = null;

  const res = await fetch(`${process.env.API_URL}/api/me`, {
    headers: {
      Accept: 'application/json',
      Authorization: `Bearer ${token}`,
    },
  });

  if (res.ok) {
    const resJson = await res.json();
    user = resJson.user;
  } else {
    console.log('unauthorized');
  }

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="grid h-screen grid-cols-[200px_4fr] grid-rows-[auto_1fr_auto]">
          <UserProvider initialUser={user}>
            <Navbar />
            <Header />
            <Main>{children}</Main>
          </UserProvider>
        </div>
      </body>
    </html>
  );
}
